from fastapi import APIRouter, HTTPException
from pydantic import BaseModel

from app.services.llm import call_llm
from app.state.resume_store import get_resume_analysis

router = APIRouter(prefix="/roadmap", tags=["Roadmap"])


class RoadmapRequest(BaseModel):
    duration: int  # 30 / 60 / 90


@router.post("/generate")
def generate_roadmap(payload: RoadmapRequest):
    analysis = get_resume_analysis()

    if not analysis:
        raise HTTPException(
            status_code=400,
            detail="Resume analysis not found. Please analyze resume first."
        )

    missing_skills = [s["name"] for s in analysis.get("missing", [])]

    prompt = f"""
You are an expert career coach.

Candidate is missing these skills:
{missing_skills}

Create a {payload.duration}-day learning roadmap.

Return ONLY valid JSON in this EXACT format:

{{
  "thirtyDay": [
    {{
      "week": 1,
      "title": "Week title",
      "tasks": [
        {{
          "id": 1,
          "title": "Task title",
          "duration": "2 hours",
          "completed": false
        }}
      ]
    }}
  ]
}}
"""

    roadmap = call_llm(prompt)

    # ✅ LLM already returns dict
    if not roadmap or "thirtyDay" not in roadmap:
        raise HTTPException(
            status_code=500,
            detail="Invalid roadmap generated by LLM"
        )

    return roadmap
